# Generated by Django 3.2.6 on 2024-07-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
