# Generated by Django 3.2.6 on 2024-07-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20240729_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
